name: Run all tests
on:
  workflow_dispatch:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_call:

jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit-tests.yml
#  run-integration-tests:
#    uses: ./.github/workflows/integration-tests.yml

