name: Run all tests
on: [ pull_request, workflow_dispatch ]
jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit-tests.yml
#  run-integration-tests:
#    uses: ./.github/workflows/integration-tests.yml

