name: Run all tests
on: [ push ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: ./tests/unit-tests.yml
      - name: Run integration tests
        uses: ./integration-tests.yml
