name: Run all tests
on:
  workflow_dispatch:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  publish-after:
    uses: ./.github/workflows/publish.yml
#  run-integration-tests:
#    uses: ./.github/workflows/integration-tests.yml

