name: Run integration tests
on: [ workflow_call ]
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Mock test run
        run: echo "No actual integration tests, checking workflow composition"