name: Run all unit tests
run-name: Run all unit tests
on: [ workflow_call ]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Build code
        run: mvn clean -e install -DskipTests=true
      - name: Run tests
        run: mvn -e test
      - name: Create report
        run:
          - mvn -e surefire-report:report
          - ls -lhat
      - name: Archive test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/site/surefire-report.html